name = "AirBorne"
uuid = "4a232ea9-7d1f-4dd8-a126-b47d2ae9e134"
authors = ["Bruno Castro Ibarburu"]
version = "1.0.0-DEV"

[deps]
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Currencies = "0fd90b74-7c1f-579e-9252-02cd883047b9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DirectSearch = "9d7617aa-e122-4445-bdd0-98866dcb605d"
DotMaps = "98454f44-f182-4945-8d34-ddde53e72162"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Bijections = ">= 0.1"
CSV = ">= 0.10"
Currencies = ">= 0.17"
DataFrames = ">= 1"
DirectSearch = ">= 0.1"
DotMaps = ">= 0.1"
HTTP = ">= 1"
Ipopt = ">= 1"
JSON = ">= 0.21"
JuMP = ">= 1"
MathOptInterface = ">= 1"
Parquet2 = ">= 0.2"
Pipe = ">= 1"
Suppressor = ">= 0.2"
Tables = ">= 1"
TestEnv = ">= 1"
julia = ">= 1"

[extras]
Currencies = "0fd90b74-7c1f-579e-9252-02cd883047b9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Currencies", "Revise", "Test", "TestSetExtensions"]
